# Generated by Django 5.2.4 on 2025-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, unique=True, verbose_name='телеграм'),
        ),
    ]
