# Generated by Django 5.2.4 on 2025-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.URLField(verbose_name='url изображения профиля'),
        ),
    ]
