# Generated by Django 5.2.4 on 2025-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.CharField(blank=True, null=True, verbose_name='url изображения профиля'),
        ),
    ]
