# Generated by Django 5.2.4 on 2025-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='именем')),
                ('description', models.CharField(max_length=200, verbose_name='описанием')),
                ('image_url', models.URLField(verbose_name='обложка группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
                'db_table': 'groups',
            },
        ),
    ]
