# Generated by Django 5.2.4 on 2025-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_channels', '0002_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image_url',
            field=models.CharField(verbose_name='обложка группы'),
        ),
    ]
