# Generated by Django 5.2.4 on 2025-07-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_channels', '0003_alter_group_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
